### ISSUE TITLE
Mobile compatible 

### ISSUE THREAD

**Issue by easa** [faslm/ajax-content-loading#15]
![Screenshot_20191106-073022~01~01](https://user-images.githubusercontent.com/6375599/68267439-b0704280-0067-11ea-9a88-42b02295b1c4.png)

**Comment by FatemehSalmani** [comment]
What should I do to fix this problem?

**Comment by easa** [comment]
> What should I do to fix this problem?

@faslm  
There is some tutorials about responsive design: 
* (best) https://w3schools.com/css/css_rwd_intro.asp 
* https://internetingishard.com/html-and-css/responsive-design 
* (good video) https://youtube.com/watch?v=fgOO9YUFlGI
* https://youtu.be/Wm6CUkswsNw?t=3269
* https://youtube.com/watch?v=srvUrASNj0s
* (farsi-seo) https://mohtava.info/mobile-optimization-guide/
